baseURL = "https://dc0d.github.io/"
title = "sketches"
# copyright = "© Copyright Notice | Kaveh Shahbazian"

languageCode = "en-us"
defaultContentLanguage = "en"
author = "Kaveh Shahbazian"

paginate = 9
preserveTaxonomyNames = true

#

theme = "hugo-vitae"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/__dc0d__"

[[params.social]]
name = "Email"
icon = "fas fa-envelope"
url = "mailto:kaveh@shahbazian.link"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
	keywords = ["programming","software development","golang","tdd","agile"]
	description = "sketches for software development"
	pagetitle = "sketches for software development"
	subtitle = "sketches for software development"
	listAuthor = true
	math = true
	avatar = "/images/logo.png"
	favicon = true
        mainSections = ["posts"]

[params.comments]
enable = false

enableRobotsTXT = true

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""
disqusShortname = ""

enableEmoji = true

[params.info]
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
gopher = "images/kash.png" # used in 404 template ( Generator: https://gopherize.me )
